//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Roitberg Lab\source\repos\ClassLibrary2\ClassLibrary2\XYZ.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ClassLibrary2 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XYZParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IXYZListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XYZParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] XYZParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XYZParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] XYZParser.FileContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XYZParser.frame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrame([NotNull] XYZParser.FrameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XYZParser.frame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrame([NotNull] XYZParser.FrameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XYZParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] XYZParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XYZParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] XYZParser.CommentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XYZParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] XYZParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XYZParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] XYZParser.LineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XYZParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] XYZParser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XYZParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] XYZParser.HeaderContext context);
}
} // namespace ClassLibrary2
